//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD_NHAPHANG
    {
        public int ID_MATHANG { get; set; }
        public int ID_HDNHAPHANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<System.DateTime> HANSUDUNG { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        public virtual MAT_HANG MAT_HANG { get; set; }
        public virtual HD_NHAPHANG HD_NHAPHANG { get; set; }
    }
}
