//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_NHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HD_NHAPHANG()
        {
            this.CTHD_NHAPHANG = new HashSet<CTHD_NHAPHANG>();
        }
    
        public int ID_HDNHAPHANG { get; set; }
        public Nullable<int> ID_NHANVIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_NHAPHANG> CTHD_NHAPHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
