//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_PHONG
    {
        public int ID_HDPHONG { get; set; }
        public Nullable<int> ID_NHANVIEN { get; set; }
        public Nullable<int> ID_PHONG { get; set; }
        public Nullable<int> ID_KHACHHANG { get; set; }
        public Nullable<int> GIOVAO { get; set; }
        public Nullable<int> GIORA { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
