//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAT_HANG()
        {
            this.CTHD_NHAPHANG = new HashSet<CTHD_NHAPHANG>();
            this.CTHD_PHONG = new HashSet<CTHD_PHONG>();
        }
    
        public int ID_MATHANG { get; set; }
        public Nullable<int> ID_NHACUNGCAP { get; set; }
        public string TEN_MATHANG { get; set; }
        public string DONVITINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_NHAPHANG> CTHD_NHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_PHONG> CTHD_PHONG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
