//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_KARAOKEEntities : DbContext
    {
        public QL_KARAOKEEntities()
            : base("name=QL_KARAOKEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CTHD_NHAPHANG> CTHD_NHAPHANG { get; set; }
        public virtual DbSet<CTHD_PHONG> CTHD_PHONG { get; set; }
        public virtual DbSet<HD_PHONG> HD_PHONG { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<LOAI_PHONG> LOAI_PHONG { get; set; }
        public virtual DbSet<MAT_HANG> MAT_HANG { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<HD_NHAPHANG> HD_NHAPHANG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
    
        public virtual ObjectResult<DEMSLMATHANG_Result> DEMSLMATHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEMSLMATHANG_Result>("DEMSLMATHANG");
        }
    
        public virtual ObjectResult<prDoanThu_Result> prDoanThu(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prDoanThu_Result>("prDoanThu", thangParameter);
        }
    
        public virtual ObjectResult<prDoanhthuPhong_Result> prDoanhthuPhong(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prDoanhthuPhong_Result>("prDoanhthuPhong", thangParameter);
        }
    }
}
