//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HD_PHONG = new HashSet<HD_PHONG>();
        }
    
        public int ID_NHANVIEN { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string TINHTRANGGD { get; set; }
        public string QUYEN { get; set; }
    
        public virtual HD_NHAPHANG HD_NHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_PHONG> HD_PHONG { get; set; }
    }
}
