//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.CTHD_PHONG = new HashSet<CTHD_PHONG>();
            this.HD_PHONG = new HashSet<HD_PHONG>();
        }
    
        public int ID_PHONG { get; set; }
        public Nullable<int> ID_LOAIPHONG { get; set; }
        public string SO_PHONG { get; set; }
        public string TRANGTHAI { get; set; }
        public string SUCCHUA { get; set; }
        public Nullable<int> GIAPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_PHONG> CTHD_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_PHONG> HD_PHONG { get; set; }
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
    }
}
